
// This file is automatically generated. Do not edit it directly.
// This is now just a re-export from our centralized initialization

import { supabase } from '../../lib/supabase/initClient';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export { supabase };
