
// This file is automatically generated. Do not edit it directly.
// This is now just a re-export from our centralized initialization

import { supabaseAdmin } from '../../lib/supabase/initServer';

// Import the supabase admin client like this:
// import { supabaseAdmin } from "@/integrations/supabase/server";

export { supabaseAdmin };
